#!/bin/bash
FILE=$1

if  [ $# -eq 1 ]; then
     if test -f "$FILE" && [[ $FILE == *.c ]]; then
        gcc $FILE -S -masm=intel -fno-asynchronous-unwind-tables
        ASMFILE=$(echo "$FILE" | cut -f 1 -d '.')
        cat "${ASMFILE}.s"
    else
        echo "'$FILE' does not exist or is not a regular file or does not end with '*.c'"

    fi

elif [ "$2" = 'o' ]; then
    if test -f "$FILE" && [[ $FILE == *.c ]]; then
        gcc $FILE -S -O2 -masm=intel -fno-asynchronous-unwind-tables
        ASMFILE=$(echo "$FILE" | cut -f 1 -d '.')
        cat "${ASMFILE}.s"
    else
        echo "'$FILE' does not exist or is not a regular file or does not end with '*.c'"

    fi
else
    echo "Usage: FILE o"
fi
   

