#!/usr/bin/env python3
import sys

def r_space(s):
    return s.replace(" ", "")

def bin_c(s):
    return ''.join(chr(int(s[i*8:i*8+8],2)) for i in range(len(s)//8))
def hex_c(s):
    s = bytes.fromhex(s).decode('ascii')
    return s


s = r_space(sys.argv[1])

try:
    print(bin_c(s))
except ValueError:
    print(hex_c(s))

